---
title: Videos
comments: false
hidden: false
tags: [videos, slides]
output: 
  blogdown::html_page: 
    css: css/camp_style.css
    self_contained: false
    toc: false
---


<style> 
.fa {font-size: 24px;}
li {line-height: 4rem !important;}
hr {background: 0;}
</style>


```{r setup, include=FALSE}
library(rmarkdown)
library(knitr)
library(magrittr)

knitr::opts_chunk$set(echo = F, warning=F, message=F)

opts_chunk$set(error=TRUE, color=NULL, message=FALSE, eval=T)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```


## Camp prep

<div style="margin-left: 4%;">

### <i class="fas fa-clipboard"></i> <span style="font-size: 90%">0.1 - </span> [Install R](install.html)

  - **Required** - *Please-please do before our first session together. Send Barbara Monaco/Derek Nagel a Teams chat or email for help.*

### <i class="fas fa-clipboard"></i> <span style="font-size: 90%">0.2 - </span> [Camp Primer](r_camp_primer.html) 

  - *Optional pre-camp intro to R and all things code*

</div>
<br>

<ul class="nav nav-pills" id="myTab" role="tablist" style="margin-top: 18px;">
<li class="nav-item active"><a class="nav-link" id="day1-tab" data-toggle="tab" href="#day1" role="tab" aria-controls="day1" aria-selected="true">`Day 1`</a></li> 
<li class="nav-item"><a class="nav-link" id="day2-tab" data-toggle="tab" href="#day2" role="tab" aria-controls="day2" aria-selected="false">`Day 2`</a></li>
<li class="nav-item"><a class="nav-link" id="day3-tab" data-toggle="tab" href="#day3" role="tab" aria-controls="day3" aria-selected="false">`Day 3`</a></li>
<li class="nav-item"><a class="nav-link" id="day4-tab" data-toggle="tab" href="#day4" role="tab" aria-controls="day4" aria-selected="false">`Day 4`</a></li> 
<li class="nav-item"><a class="nav-link" id="day5-tab" data-toggle="tab" href="#day5" role="tab" aria-controls="day5" aria-selected="false">`Day 5`</a></li> 
<li class="nav-item"><a class="nav-link" id="day6-tab" data-toggle="tab" href="#day6" role="tab" aria-controls="day6" aria-selected="false">`Day 6`</a></li></ul>

<div class="well tab-content" id="myTabContent" style="background-color: white;">
<div class="tab-pane fade active in" id="day1" role="tabpanel" aria-labelledby="day1-tab">

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">1.1 - </span> [Welcome to open source](videos/01-1-welcome.html)  
  
- [Notes and code examples](day1.html#welcome) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-1-Welcome.html) 


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">1.2 - </span> [R tour](videos/01-2-r-tour.html) 

- [Notes and code examples](day1.html#rstudio-tour) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-2-R-tour.html) 


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">1.3 - </span> [R bakery](videos/01-3-r-bakery.html) 

- [Notes and code examples](day1.html#names-and-things) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-3-R-bakery.html)


### <i class="fa fa-video-camera" ></i> <span style="font-size: 90%">1.4 - </span> Tables of data

- [Notes and code examples](day1.html#tidy-tables-and-dataframes) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-4-Tables-and-dataframes#1)


### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercises

- [Coming soon...](https://tidy-mn.github.io/R-camp-penguins/exercise/day1/exercises.html)

</div>

<div class="tab-pane fade" id="day2" role="tabpanel" aria-labelledby="day2-tab">


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">2.1 - </span> Data wrangling  
  
- [Notes and code examples](day2.html) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day2/02-1-Data_wrangling.html#1)



### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">2.2 - </span> Fork in the road: if_else and case_when 
  
- [Notes and code examples](day2.html#forks) 
- Slides


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">2.3 - </span> Boil it down: Summarize the data  
  
- [Notes and code examples](day2.html#summarize) 
- Slides


### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercises

- [Describe penguin populations](https://tidy-mn.github.io/R-camp-penguins/page/exercise/describe_penguin_populations.html)
- [Guess Who! *Hint: I'm a penguin*](https://tidy-mn.github.io/R-camp-penguins/page/exercise/find_the_penguin.html)

</div>

<div class="tab-pane fade" id="day3" role="tabpanel" aria-labelledby="day3-tab">  

### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercises

- Derek's radioactive joining and dating

</div> 

<div class="tab-pane fade" id="day4" role="tabpanel" aria-labelledby="day4-tab">   

### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercises

- [ggplot exercises](https://tidy-mn.github.io/R-camp-penguins/page/exercise/day4/4_1_ggplot_exercises.html)

</div> 

<div class="tab-pane fade" id="day5" role="tabpanel" aria-labelledby="day5-tab">  

### Kristie slides?

- 5.1: [Spatial awareness and GIS](https://tidy-mn.github.io/R-camp-penguins/page/exercise/day5/intro_to_gis.html)
- 5.2: [sf: Simple features package](https://tidy-mn.github.io/R-camp-penguins/page/exercise/day5/sf.html)
- [Points, Lines, and Polygons](https://tidy-mn.github.io/R-camp-penguins/page/exercise/day5/5_3_points_lines_polygons.html)


### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Map exercises

- [Homeward bound](https://tidy-mn.github.io/R-camp-penguins/page/exercise/day5/5_homeward_bound.html)


</div> 


<div class="tab-pane fade" id="day6" role="tabpanel" aria-labelledby="day6-tab"> 

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">1.1 - </span> [R markdown: Reports, dashboards, presentations, and webpages]()  

</div>

</div>
