baseurl = "r-camps"
DefaultContentLanguage = "en"
title = "Learn R"
theme = "beautifulhugo"
summaryLength = 20
metaDataFormat = "yaml"
#highlightjsLang = ["r"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "static/data/.*", "content/page/data/.*", "page/data/*"]
#relativeURLs = true
uglyURLs = true

[Params]
  #useHLJS = true
  #homeTitle = "Home page header" # Set a different text for the header on the home page
  #themeColor = ".theme-base-08"
  #subtitle = "Subtitle text here"
  logo     = "images/penguins_circle1.png"
  #favicon = "images/penguins_circle1.png"
  #logo    = "https://ui-avatars.com/api/?background=363636&color=fff&size=128&font-size=.6&name=R&rounded=true"
  favicon = "https://ui-avatars.com/api/?background=2E2E2E&color=fff&font-size=.7&name=R&size=128&rounded=true"
  dateFormat = "January 2, 2006"
  showthedate = false
  commit = true
  showsocial = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false
  showDatesOnPosts = false
  showDatesOnPages = false
  showDates = false
  #relativeURLs = true
  uglyURLs = true
  highlightjsVersion = "9.13.1"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r"]
  highlightjsTheme = "github"

[Author]
  name = "Pengu"
  #email = ""
  #github = "learnr"
  #twitter = ""
  #gitlab = "username"


    
[[menu.main]]
    identifier = "Training"
    name = "Training"
    weight = 1

[[menu.main]]
    parent = "Training"
    name = "Agenda"
    url = "page/agenda.html"
    weight = 1

[[menu.main]]
    parent = "Training"
    name = "Camp Primer"
    url = "page/r_camp_primer.html"
    weight = 1  
  
[[menu.main]]
    parent = "Training"
    name = "Videos"
    url = "page/videos.html"
    weight = 1     

[[menu.main]]
    parent = "Training"
    name = "Day 1"
    url = "page/day1.html"
    weight = 2

[[menu.main]]
    parent = "Training"
    name = "Day 2"
    url = "page/day2.html"
    weight = 2

[[menu.main]]
    parent = "Training"
    name = "Day 3"
    url = "page/day3.html"
    weight = 2

[[menu.main]]
    parent = "Training"
    name = "Day 4"
    url = "page/day4.html"
    weight = 2  
    
[[menu.main]]
    parent = "Training"
    name = "Day 5"
    url = "page/day5.html"
    weight = 2 
    
[[menu.main]]
    parent = "Training"
    name = "Day 6"
    url = "page/day6.html"
    weight = 2   

[[menu.main]]
    name = "Install R"
    url = "page/install.html"
    weight = 2


[[menu.main]]
    name = "Community"
    url = "page/community.html"
    weight = 3

[[menu.main]]
    name = "Help"
    url = "page/help.html"
    weight = 4
