---
title: Welcome
comments: false
hidden: false
date: "2023-11-30"
output: 
  blogdown::html_page: 
    css: page/css/camp_style.css
    self_contained: false
    toc: false
---


<style> 
.fa {font-size: 24px;}
li {line-height: 4rem !important;}
hr {background: 0;}
</style>


```{r setup, include=FALSE}
library(rmarkdown)
library(knitr)
library(magrittr)

knitr::opts_chunk$set(echo = F, warning=F, message=F)

opts_chunk$set(error=TRUE, color=NULL, message=FALSE, eval=T)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```


<h2 style="margin-top: 28px;"> Camp prep </h2>

<div style="margin-left: 3%;">

### <i class="fas fa-clipboard"></i> [Install R](page/install.html) {-}

### <i class="fas fa-clipboard"></i> [Camp Primer](page/r_camp_primer.html) {-}

</div>

<h2> Live courses
  <span style="background: linear-gradient(90deg, #e63946, #ff9f43); color: #fff; font-size: 0.7em; font-weight: 700; padding: 0.2em 0.6em; border-radius: 1em; margin-left: 0.5em; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25); text-transform: uppercase; letter-spacing: 0.5px;">
    NEW! 
  </span> 
</h2>

<ul class="nav nav-pills" id="myTab" role="tablist" style="margin-top: 18px;">
<li class="nav-item"><a class="nav-link" id="reports-tab" data-toggle="tab" href="#reports" role="tab" aria-controls="reports" aria-selected="false">`Reports`</a></li>
<li class="nav-item"><a class="nav-link" id="reports-tab" data-toggle="tab" href="#text" role="tab" aria-controls="text" aria-selected="false">`Text analysis`</a></li>
<li class="nav-item"><a class="nav-link" id="reports-tab" data-toggle="tab" href="#stats" role="tab" aria-controls="stats" aria-selected="false">`Stats`</a></li>
<li class="nav-item"><a class="nav-link" id="after-camp-tab" data-toggle="tab" href="#after-camp" role="tab" aria-controls="after-camp" aria-selected="false">`+After camp`</a></li>
</ul>

<div class="tab-pane fade" id="reports" role="tabpanel" aria-labelledby="reports-tab"> 

<h2 style="margin-top: 14px;">Reports </h2>

### <i class="fas fa-clipboard"></i> <span style="font-size: 90%">1 - </span> [Markdown crash course](page/markdown_crash_course.html)

### <i class="fas fa-clipboard"></i> <span style="font-size: 90%">2 - </span> [Quarto documents](page/publish_data_with_quarto.html)

</div>


<div class="tab-pane fade" id="text" role="tabpanel" aria-labelledby="text-tab"> 

<h2 style="margin-top: 14px;">Text and qualitative analysis  </h2>

### <i class="fas fa-clipboard"></i> <span style="font-size: 90%">1 - </span> [Text Analysis in R: From Raw to Ready](page/raw_to_ready.html)


</div>


<div class="tab-pane fade" id="stats" role="tabpanel" aria-labelledby="stats-tab"> 

<h2 style="margin-top: 14px;">Statistics in R  </h2>

### <i class="fas fa-clipboard"></i> <span style="font-size: 90%">1 - </span> Coming soon...


</div>


<div class="tab-pane fade" id="after-camp" role="tabpanel" aria-labelledby="after-camp-tab"> 

### Join the community

> Join us at our weekly Tidy Tuesday meeting on Teams: [MN R users](https://teams.microsoft.com/l/team/19%3a92cfbaafbda9430aa1a480d7994829cd%40thread.skype/conversations?groupId=44cb2676-6137-4f1c-b7d0-9fbd672f9c65&tenantId=eb14b046-24c4-4519-8f26-b89c2159828c)


### Continue learning

Here's a collection of our <span class="teal">**favorite**</span> resources created by the global R community.

**Stats**

- <i class="fa fa-video-camera teal"></i> [Regression and Linear Models lab](https://www.youtube.com/watch?v=j5mu5XcJD_w&list=PLik6fAQnSI93eBVuAONFBCVdOd7VFhKQX&index=8) *(20 min)*
    - Notes - [Download the Quarto.qmd](https://tidy-mn.github.io/R-camp-penguins/data/stat220_regression_prelab.qmd)
- <i class="fa-solid fa-display teal"></i> [Statistics with Teacup Giraffes](https://tinystats.github.io/teacups-giraffes-and-statistics/01_introToR.html)

**Plots**

- <i class="fa fa-video-camera teal"></i> [Annotate with text and colors](https://www.youtube.com/watch?v=TGU-ekc8Tyg) *(33 min)*
- <i class="fa fa-video-camera teal"></i> [Make aRt with ggplot](https://www.youtube.com/watch?v=h0i6KAahLY8) *(35 min)*
- <i class="fa fa-video-camera teal"></i> [Take a sad plot and make it...](https://www.youtube.com/watch?v=JeRRSGWODBQ) *(54 min)*

**Exploratory analysis**

- <i class="fa fa-video-camera teal"></i> [Maps: Squirrels in New York](https://www.youtube.com/watch?v=6GV9sAD6Pi0) *(1 hr)*
- <i class="fa fa-video-camera teal"></i> [Survey results: Thanksgiving dinner](https://www.youtube.com/watch?v=rxJZT0duwfU) *(1 hr)*
- <i class="fa fa-video-camera teal"></i> [Survey results: Multiple choice and intro to *purrr*](https://www.youtube.com/watch?v=uG3igAGX7UE) *(40 min)*
- <i class="fa fa-video-camera teal"></i> [Bob Ross paintings](https://www.youtube.com/watch?v=sD993H5FBIY) *(1 hr)*


**Tidyverse**

- <i class="fa fa-video-camera teal"></i> [10  tidyverse tricks](https://www.youtube.com/watch?v=NDHSBUN_rVU) *(20 min)*  


**Courses**

These Coursera courses are <span class="teal">**FREE**</span> to `audit`, you do not need to give them money.

- <i class="fa-solid fa-display teal"></i> [John Hopkins: Reproducible research in R](https://www.coursera.org/learn/reproducible-research)


**For the EPI's in the room**

- <i class="fa-solid fa-book teal"></i> [The Epidemiologist R Handbook](https://www.epirhandbook.com/en/transition-to-r.html)


</div>

<h2> Video courses </h2>

<ul class="nav nav-pills" id="myTab" role="tablist" style="margin-top: 18px;">
<li class="nav-item active"><a class="nav-link" id="day1-tab" data-toggle="tab" href="#day1" role="tab" aria-controls="day1" aria-selected="true">`Tidy`</a></li> 
<li class="nav-item"><a class="nav-link" id="day2-tab" data-toggle="tab" href="#day2" role="tab" aria-controls="day2" aria-selected="false">`Wrangle`</a></li>
<li class="nav-item"><a class="nav-link" id="day3-tab" data-toggle="tab" href="#day3" role="tab" aria-controls="day3" aria-selected="false">`ggplot`</a></li>
<li class="nav-item"><a class="nav-link" id="day4-tab" data-toggle="tab" href="#day4" role="tab" aria-controls="day4" aria-selected="false">`Maps`</a></li> 
<li class="nav-item"><a class="nav-link" id="day5-tab" data-toggle="tab" href="#day5" role="tab" aria-controls="day5" aria-selected="false">`Joins`</a></li> 
<li class="nav-item"><a class="nav-link" id="day6-tab" data-toggle="tab" href="#day6" role="tab" aria-controls="day6" aria-selected="false">`Pivot`</a></li>
</ul>

<div class="well tab-content" id="myTabContent" style="background-color: white;">
<div class="tab-pane fade active in" id="day1" role="tabpanel" aria-labelledby="day1-tab">

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">1.1 - </span> [Welcome to open source](page/videos/day1/01-1-welcome.html)  
  
- [Notes and code examples](page/day1.html#welcome) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-1-Welcome.html) 


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">1.2 - </span> [R tour](page/videos/day1/01-2-r-tour.html) 

- [Notes and code examples](page/day1.html#r-tour) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-2-R-tour.html) 


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">1.3 - </span> [R bakery](page/videos/day1/01-3-r-bakery.html) 

- [Notes and code examples](page/day1.html#r-bakery) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-3-R-bakery.html)


### <i class="fa fa-video-camera" ></i> <span style="font-size: 90%">1.4 - </span> [Tidy tables](page/videos/day1/01-4-tidy-tables.html)

- [Notes and code examples](page/day1.html#tidy-tables) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-4-Tables-and-dataframes#1)


### <i class="fa fa-video-camera" ></i> <span style="font-size: 90%">1.5 - </span> [Sizing up the data](page/videos/day1/01-5-size-up-the-data.html)

- [Notes and code examples](page/day1.html#sizing-up-the-data) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day1/01-4-Tables-and-dataframes#1)

### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercise Day

- [AGENDA](page/exercise/day1/agenda.html)
- [Exercise 1 - Taking inventory](page/exercise/day1/inventory_duty.html)
- [Exercise 2 - Auditor in training](page/exercise/day1/inventory_duty_expanded.html)


</div>

<div class="tab-pane fade" id="day2" role="tabpanel" aria-labelledby="day2-tab">


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">2.1 - </span> [Data wrangling](page/videos/day2/02-1-data-wrangling.html)
  
- [Notes and code examples](page/day2.html) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day2/02-1-Data-wrangling.html#1)


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">2.2 - </span> [Forks in the road: `if_else` + `case_when`](page/videos/day2/02-2-forks-in-the-road)
  
- [Notes and code examples](page/day2.html#forks-in-the-road-if_else-case_when)
- [Slides](https://tidy-mn.github.io/R-camp-slides/day2/02-2-Forks-in-the-road.html)


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">2.3 - </span> [Simmer it down: Summarize the data](page/videos/day2/02-3-simmer-it-down.html)  
  
- [Notes and code examples](page/day2.html#simmer-it-down-summarize-the-data) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day2/02-3-Boil-it-down.html#1)


### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercise Day

- [AGENDA](page/exercise/agenda.html)
- [Exercise 1 - Describe penguin populations](page/exercise/describe_penguin_populations.html)
- [Exercise 2 - Guess Who! *Hint: I'm a penguin*](page/exercise/find_the_penguin.html)

</div>


<div class="tab-pane fade" id="day3" role="tabpanel" aria-labelledby="day3-tab">  

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">3.1 - </span> [ggplot: A grammar of graphics](page/videos/day3/03-1-ggplot.html)
  
- [Notes and code examples](page/day3.html) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day3/03-1-Plots-graphics-grammar.html#1)


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">3.2 - </span> [ggplot: Facets, colors, and labels](page/videos/day3/03-2-ggplot-facets-colors-labels.html)
  
- [Notes and code examples](page/day3.html#ggplot-facets-colors-and-labels) 
- [Slides](https://tidy-mn.github.io/R-camp-slides/day3/03-2-Facets-labels-colors.html#1)


### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercise Day

- [Exercise 1 - ggplot](page/exercise/day3/3-1-ggplot_exercises.html)
- [Exercise 2 - ggplot: The remix](page/exercise/day3/3-2-ggplot_exercises.html)

</div> 


<div class="tab-pane fade" id="day4" role="tabpanel" aria-labelledby="day4-tab">  

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">4.1 - </span> [Maps: GIS and Coordinate reference systems (CRS)](page/videos/day4/04-1-maps-gis-crs.html) 

- [Notes and code examples](page/day4.html)

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">4.2 - </span> [Points, Lines, and Polygons](page/videos/day4/04-2-points-lines-polygons.html)

- [Notes and code examples](page/day4.html#points-lines-and-polygons)

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">4.3 - </span> [**sf** is so awesome](page/videos/day4/04-3-sf-spatial-analysis-part1.html) 

- [Notes and code examples](page/day4.html#sf-is-so-awesome)

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">4.4 - </span> [**sf** spatial analysis (Part 2)](page/videos/day4/04-4-sf-spatial-analysis-part2.html)

- [Notes and code examples](page/day4.html#sf-spatial-analysis-part-2)



### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercise Day

- [Exercise 1 - Homeward bound](page/exercise/day4/01-homeward-bound.html)
- [Exercise 2 - Healthy forests](page/exercise/day4/02-forest-health-map.html)

</div> 


<div class="tab-pane fade" id="day5" role="tabpanel" aria-labelledby="day5-tab">   

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">5.1 - </span> [Dataframe SMASH: **Joining tables**](page/videos/day5/05-1-smash-table-joins.html)

- [Notes and code examples](page/day5.html)
- [Slides](https://tidy-mn.github.io/R-camp-slides/day5/05-1-SMASH-table-joins.html#1)

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">5.2 - </span> [**lubridate:** Date and time travel](page/videos/day5/05-2-lubridate-date-and-time-travel.html)

- [Notes and code examples](page/day5.html#lubridate-date-and-time-travel)
- [Slides](https://tidy-mn.github.io/R-camp-slides/day5/05-2-date-and-time-travel#1)


### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercise Day

- Exercise 1 - [**Joins: A fishy dinner**](page/exercise/day5/05-1-left-and-anti-joins.html)
- Exercise 2 - [**Date mischief with heat**](page/exercise/day5/05-2-date-mischief-and-data-joins.html)


</div> 


<div class="tab-pane fade" id="day6" role="tabpanel" aria-labelledby="day6-tab"> 

### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">6.1 - </span> [Pivoting data: **Wide & long format**](page/videos/day6/06-1-pivot-wide-long-format.html)

- [Slides](https://tidy-mn.github.io/R-camp-slides/day6/06-1-pivot-wider.html#1)


### <i class="fa fa-video-camera"></i> <span style="font-size: 90%">6.2 - </span> Tutorial: Reports in R *(from our Posit friends)*

Download the [Quarto file](https://tidy-mn.github.io/R-camp-penguins/data/index.qmd) and follow along with the [Get started](https://www.youtube.com/watch?v=_f3latmOhew) video from the Tutorial below.

- [Download the Quarto file](https://tidy-mn.github.io/R-camp-penguins/data/index.qmd)
- [Tutorial: Hello, Quarto!](https://quarto.org/docs/get-started/hello/rstudio.html)


### <i class="fa fa-birthday-cake" aria-hidden="true"></i> Exercise Day

- Download: [my_report.qmd](https://tidy-mn.github.io/R-camp-penguins/data/my_report.qmd)

</div>




</div>
