---
title: 'Exercise: Filtering and case_when'
author: "Abigail Stamm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1: filtering data

The goal of this exercise is to filter a dataset using repeated filter commands until you only have one row of data left.

Using the `palmerpenguins` dataset, isolate a penguin who meets one of the following sets of criteria. What is its study number?

1. I am a female Adelie penguin hatched on November 12th on Biscoe Island. I was part of the latest study.
1. I am a male Chinstrap penguin weighing over 4kg. My culmen is over 50mm long, but my flippers are less than 200mm long. 
1. I am a female Gentoo penguin weighing over 5kg, but my culmen is shorter at under 45mm. 

For a greater challenge, try to isolate these penguins.

1. I have the lowest weight of the male penguins.
1. I am the heaviest female Adelie penguin.
1. I have the longest flippers of the Adelie penguins on Dream Island.


## Exercise 2: using case_when

Select the same penguin that you selected above. Create a new variable using case_when that uses the criteria provided to identify your selected penguin and and only your selected penguin in your dataset.
