---
title: 'Exercise: Describing penguin populations with `summarize()`'
author: "Abigail Stamm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summarize data about penguin populations

The goal of this exercise is to create summary datasets that answer specific questions about the penguin populations. Use the `penguins` dataset in the `palmerpenguins` package. Datasets get steadily more complex. Ask for help if you get stuck or need a hint.


### Compare flipper lengths

Create a dataset that summarizes the flipper lengths of the penguin populations by species. Calculate the minimum, maximum, and average flipper lengths of each penguin species. 

1. Which penguin species has the shortest flippers?
1. Is there a flipper length range that includes all three penguin species?

<details>
<summary>Code hint</summary>
  Example:  
  `group_by(data, x)`  
  `summarize(data, x = min(y))`  
  `ungroup(data, x)`   
  Remember to account for `NA` values.  

<details>
<summary>Advanced code hint</summary>
  Example:  
  `data %>% group_by(species)`  
  `data %>% summarize(min_length = min(flipper_length_mm))`  
  `data %>% ungroup(species)`  
  
<details>
<summary>Precise code hint</summary>
  Example:  
  <pre>
  <code>
  data %>% group_by(species) %>%
      summarize(min_length = min(flipper_length_mm, na.rm = TRUE)) %>%
      ungroup(species)
  </code>
  </pre>
</details>
</details>
</details>



### Compare weights

Create a dataset that summarizes the weights of the penguin populations by species and island. Calculate the minimum, maximum, and average weights of each group. 

1. Which penguin species is the heaviest?
1. On which island are Adelie penguins the heaviest?

<details>
<summary>Code hint</summary>
  Example:  
  `group_by(data, x)`  
  `summarize(data, x = min(y))`  
  `ungroup(data, x)`   
  Remember to account for `NA` values.  

<details>
<summary>Advanced code hint</summary>
  Example:  
  `data %>% group_by(species, island)`  
  `data %>% summarize(min_length = min(body_mass_g))`  
  `data %>% ungroup(species, island)`  
  
<details>
<summary>Precise code hint</summary>
  Example:  
  <pre>
  <code>
  data %>% group_by(species, island) %>%
      summarize(min_weight = min(body_mass_g, na.rm = TRUE),
                max_weight = max(body_mass_g, na.rm = TRUE)) %>%
      ungroup(species, island)
  </code>
  </pre>
</details>
</details>
</details>



### Compare penguin bills

Create a dataset that summarizes the bill lengths and depths of the penguin populations by species, sex, and island. Calculate the minimum, maximum, and average bill lengths and depths of each group. 

1. In general, do male and female bills tend to be the same length and depth? If not, how do they differ?
1. Do the groups with the longest bills also have the deepest bills? Do the groups with the shortest bills have the shallowest?
1. From the table, would you guess bill size is most associated with species, sex, or island?


<details>
<summary>Code hint</summary>
  Example:  
  `group_by(data, x)`  
  `summarize(data, x = min(y))`  
  `ungroup(data, x)`   
  Remember to account for `NA` values.  

<details>
<summary>Advanced code hint</summary>
  Example:  
  `data %>% group_by(species, island, sex)`  
  `data %>% summarize(min_depth = min(bill_depth_mm))`  
  `data %>% ungroup(species, island, sex)`  
  
<details>
<summary>Precise code hint</summary>
  Example:  
  <pre>
  <code>
  data %>% group_by(species, island, sex) %>%
      summarize(min_depth = min(bill_depth_mm, na.rm = TRUE),
                max_length = max(bill_length_mm, na.rm = TRUE)) %>%
      ungroup(species, island, sex)
  </code>
  </pre>
</details>
</details>
</details>





