---
title: Guess who!
author: "Abigail Stamm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1: filtering data

The goal of this exercise is to pare down a dataset using the filter function multiple times until you only have one row of data left. This game is a throw back to those days on long road trips when you were down to one last game... the game of Guess Who. You were BORED because you had already played all the games, done all the puzzles, noone would stop for snacks, and you were still miles from home. So you began, Am I bigger than a bread box? Am I the color green? In this exercise you are writing code to winnow down the list of possibilities. FUN STUFF! Pre-hint - if you are new to R, you might want to begin by using multiple lines of code, but in the end you will able to write this in only one filter function with multiple criteria within.

Using the `penguins` dataset in the `palmerpenguins` package, use the filter function multiple times to find the penguin that meets one of the following sets of criteria. What is its study number?

1. I am a female Adelie penguin hatched on November 12th on Biscoe Island. I was part of the latest study.
1. I am a male Chinstrap penguin weighing over 4kg. My bill is over 5cm long, but my flippers are less than 20cm long. 
1. I am a female Gentoo penguin weighing over 5kg, but my bill is shorter at under 4.5cm long. 

For a greater challenge, try to isolate these penguins.

1. I have the lowest weight of the male penguins.
1. I am the heaviest female Adelie penguin.
1. I have the longest flippers of the Adelie penguins on Dream Island.


<details>
<summary>**CODE HINT**</summary>
  Example: 
  `filter(data, x < 0)`  
  Remember to account for `NA` values.

<details>
<summary>**ADVANCED *CODE HINT**</summary>
  Example:
  `filter(body_mass_g > 4000)`
  
<details>
<summary>**PRECISE CODE HINT**</summary>
  Example:
  `filter(penguins, body_mass_g == min(body_mass_g, na.rm = TRUE))`
  
</details>
</details>
</details>


## Exercise 2: using case_when

Select the same penguin that you selected above. Create a new TRUE/FALSE variable using case_when that uses the criteria provided to identify your selected penguin and only your selected penguin as *TRUE*. This time your answer will be available as a variable in your dataset.

<details>
<summary>**CODE HINT**</summary>
  Example: 
  `case_when(x == y ~ TRUE, .default = FALSE)`  

<details>
<summary>**ADVANCED *CODE HINT**</summary>
  Example:
  `case_when(body_mass_g > 4000 ~ TRUE, .default = FALSE)`
  
<details>
<summary>**PRECISE CODE HINT**</summary>
  Example:
  `mutate(penguins, subject = case_when(body_mass_g > 4000 & bill_length_mm > 50 ~ TRUE, .default = FALSE))`
  
</details>
</details>
</details>



